
// Generated by https://quicktype.io

export interface FullCollection {
    id_productos_coleccion: string;
    id: number;
    usuario_id: number;
    producto_id: number;
    titulo: string;
    fecha_creacion: string;
    categoria: string;
    codigo: string;
    username: string;
    email: string;
    password: string;
    direccion: string;
    nombre: string;
    apellidos: string;
    avatar: string;
    fecha_nacimiento: string;
    trusted: number;
    rating: number;
    fecha_registro: string;
}
